//! Circuit name → witness dylib + short name (mirrors src/witness.ts CIRCUIT_MAP).
pub const Spec = struct {
    zkey: []const u8,
    lib: []const u8,
    short: []const u8,
};

pub const CircuitId = enum {
    register_main,
    shuffle_1_deck_52_main,
    shuffle_6_deck_52_main,
    shuffle_8_deck_52_main,
    poker_share_hashout_main,
    poker_showdown_hashout_main,
    baccarat_share_hashout_main,
    baccarat_showdown_hashout_main,
    war_share_hashout_main,
    war_showdown_hashout_main,
    blackjack_share_hashout_main,
    blackjack_action_hashout_main,
    blackjack_showdown_hashout_main,
    shuffle_1_deck_37_main,
    shuffle_1_deck_38_main,
    roulette_share_hashout_main,
    roulette_bet_37_main,
    roulette_bet_38_main,
    roulette_showdown_37_hashout_main,
    roulette_showdown_38_hashout_main,
    shuffle_2_dice_6_main,
    craps_share_hashout_main,
    craps_bet_main,
    craps_showdown_hashout_main,
    shuffle_1_deck_80_main,
    keno_share_hashout_main,
    keno_bet_main,
    keno_showdown_hashout_main,
    shuffle_3_reel_22_main,
    shuffle_5_reel_22_main,
    slot_share_3_reel_hashout_main,
    slot_share_5_reel_hashout_main,
    slot_showdown_3_reel_hashout_main,
    slot_showdown_5_reel_hashout_main,
    shuffle_1_deck_75_main,
    shuffle_1_deck_90_main,
    bingo_share_hashout_main,
    bingo_card_75_main,
    bingo_card_90_main,
    bingo_showdown_75_hashout_main,
    bingo_showdown_90_hashout_main,

    pub fn spec(self: CircuitId) Spec {
        return switch (self) {
            .register_main => .{ .zkey = "register_main", .lib = "zkcasino", .short = "register" },
            .shuffle_1_deck_52_main => .{ .zkey = "shuffle_1_deck_52_main", .lib = "zkcasino-shuffle-1-deck-52", .short = "shuffle_1_deck_52" },
            .shuffle_6_deck_52_main => .{ .zkey = "shuffle_6_deck_52_main", .lib = "zkcasino-shuffle-6-deck-52", .short = "shuffle_6_deck_52" },
            .shuffle_8_deck_52_main => .{ .zkey = "shuffle_8_deck_52_main", .lib = "zkcasino-shuffle-8-deck-52", .short = "shuffle_8_deck_52" },
            .poker_share_hashout_main => .{ .zkey = "poker_share_hashout_main", .lib = "zkcasino-poker", .short = "poker_share" },
            .poker_showdown_hashout_main => .{ .zkey = "poker_showdown_hashout_main", .lib = "zkcasino-poker", .short = "poker_showdown" },
            .baccarat_share_hashout_main => .{ .zkey = "baccarat_share_hashout_main", .lib = "zkcasino-baccarat", .short = "baccarat_share" },
            .baccarat_showdown_hashout_main => .{ .zkey = "baccarat_showdown_hashout_main", .lib = "zkcasino-baccarat", .short = "baccarat_showdown" },
            .war_share_hashout_main => .{ .zkey = "war_share_hashout_main", .lib = "zkcasino-war", .short = "war_share" },
            .war_showdown_hashout_main => .{ .zkey = "war_showdown_hashout_main", .lib = "zkcasino-war", .short = "war_showdown" },
            .blackjack_share_hashout_main => .{ .zkey = "blackjack_share_hashout_main", .lib = "zkcasino-blackjack", .short = "blackjack_share" },
            .blackjack_action_hashout_main => .{ .zkey = "blackjack_action_hashout_main", .lib = "zkcasino-blackjack", .short = "blackjack_action" },
            .blackjack_showdown_hashout_main => .{ .zkey = "blackjack_showdown_hashout_main", .lib = "zkcasino-blackjack", .short = "blackjack_showdown" },
            .shuffle_1_deck_37_main => .{ .zkey = "shuffle_1_deck_37_main", .lib = "zkcasino-shuffle-1-deck-37", .short = "shuffle_1_deck_37" },
            .shuffle_1_deck_38_main => .{ .zkey = "shuffle_1_deck_38_main", .lib = "zkcasino-shuffle-1-deck-38", .short = "shuffle_1_deck_38" },
            .roulette_share_hashout_main => .{ .zkey = "roulette_share_hashout_main", .lib = "zkcasino-roulette", .short = "roulette_share" },
            .roulette_bet_37_main => .{ .zkey = "roulette_bet_37_main", .lib = "zkcasino-roulette", .short = "roulette_bet_37" },
            .roulette_bet_38_main => .{ .zkey = "roulette_bet_38_main", .lib = "zkcasino-roulette", .short = "roulette_bet_38" },
            .roulette_showdown_37_hashout_main => .{ .zkey = "roulette_showdown_37_hashout_main", .lib = "zkcasino-roulette", .short = "roulette_showdown_37" },
            .roulette_showdown_38_hashout_main => .{ .zkey = "roulette_showdown_38_hashout_main", .lib = "zkcasino-roulette", .short = "roulette_showdown_38" },
            .shuffle_2_dice_6_main => .{ .zkey = "shuffle_2_dice_6_main", .lib = "zkcasino-shuffle-2-dice-6", .short = "shuffle_2_dice_6" },
            .craps_share_hashout_main => .{ .zkey = "craps_share_hashout_main", .lib = "zkcasino-craps", .short = "craps_share" },
            .craps_bet_main => .{ .zkey = "craps_bet_main", .lib = "zkcasino-craps", .short = "craps_bet" },
            .craps_showdown_hashout_main => .{ .zkey = "craps_showdown_hashout_main", .lib = "zkcasino-craps", .short = "craps_showdown" },
            .shuffle_1_deck_80_main => .{ .zkey = "shuffle_1_deck_80_main", .lib = "zkcasino-shuffle-1-deck-80", .short = "shuffle_1_deck_80" },
            .keno_share_hashout_main => .{ .zkey = "keno_share_hashout_main", .lib = "zkcasino-keno", .short = "keno_share" },
            .keno_bet_main => .{ .zkey = "keno_bet_main", .lib = "zkcasino-keno", .short = "keno_bet" },
            .keno_showdown_hashout_main => .{ .zkey = "keno_showdown_hashout_main", .lib = "zkcasino-keno", .short = "keno_showdown" },
            .shuffle_3_reel_22_main => .{ .zkey = "shuffle_3_reel_22_main", .lib = "zkcasino-shuffle-3-reel-22", .short = "shuffle_3_reel_22" },
            .shuffle_5_reel_22_main => .{ .zkey = "shuffle_5_reel_22_main", .lib = "zkcasino-shuffle-5-reel-22", .short = "shuffle_5_reel_22" },
            .slot_share_3_reel_hashout_main => .{ .zkey = "slot_share_3_reel_hashout_main", .lib = "zkcasino-slots", .short = "slot_share_3_reel" },
            .slot_share_5_reel_hashout_main => .{ .zkey = "slot_share_5_reel_hashout_main", .lib = "zkcasino-slots", .short = "slot_share_5_reel" },
            .slot_showdown_3_reel_hashout_main => .{ .zkey = "slot_showdown_3_reel_hashout_main", .lib = "zkcasino-slots", .short = "slot_showdown_3_reel" },
            .slot_showdown_5_reel_hashout_main => .{ .zkey = "slot_showdown_5_reel_hashout_main", .lib = "zkcasino-slots", .short = "slot_showdown_5_reel" },
            .shuffle_1_deck_75_main => .{ .zkey = "shuffle_1_deck_75_main", .lib = "zkcasino-shuffle-1-deck-75", .short = "shuffle_1_deck_75" },
            .shuffle_1_deck_90_main => .{ .zkey = "shuffle_1_deck_90_main", .lib = "zkcasino-shuffle-1-deck-90", .short = "shuffle_1_deck_90" },
            .bingo_share_hashout_main => .{ .zkey = "bingo_share_hashout_main", .lib = "zkcasino-bingo", .short = "bingo_share" },
            .bingo_card_75_main => .{ .zkey = "bingo_card_75_main", .lib = "zkcasino-bingo", .short = "bingo_card_75" },
            .bingo_card_90_main => .{ .zkey = "bingo_card_90_main", .lib = "zkcasino-bingo", .short = "bingo_card_90" },
            .bingo_showdown_75_hashout_main => .{ .zkey = "bingo_showdown_75_hashout_main", .lib = "zkcasino-bingo", .short = "bingo_showdown_75" },
            .bingo_showdown_90_hashout_main => .{ .zkey = "bingo_showdown_90_hashout_main", .lib = "zkcasino-bingo", .short = "bingo_showdown_90" },
        };
    }
};
